# Generated by Django 5.2.6 on 2026-05-21 11:03

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('groups', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('CALCULATED', 'Calcule'), ('ACCEPTED', 'Accepte'), ('EXPIRED', 'Expire'), ('CANCELLED', 'Annule')], default='DRAFT', max_length=20)),
                ('product_type', models.CharField(choices=[('AUTO', 'Automobile'), ('MOTO', 'Moto'), ('FLEET', 'Flotte'), ('TRAILER', 'Remorque'), ('GARAGE', 'Garage')], default='AUTO', max_length=20)),
                ('periodicity', models.CharField(choices=[('JOURS', 'Jours'), ('MOIS', 'Mois'), ('ANNEES', 'Annees')], default='MOIS', max_length=20)),
                ('duration', models.PositiveSmallIntegerField(default=12)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('coverage_options', models.JSONField(blank=True, default=list)),
                ('civil_liability_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('premium_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('fees_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='clients.client')),
                ('contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotes', to=settings.AUTH_USER_MODEL)),
                ('partner_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='groups.partnergroup')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
