# Generated by Django 5.2.6 on 2026-05-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_quote_ass_product_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='product_type',
            field=models.CharField(choices=[('AUTO', 'Automobile'), ('MOTO', 'Moto'), ('FLEET', 'Flotte'), ('TRAILER', 'Remorque'), ('SCHOOL_BUS', 'Bus ecole'), ('GARAGE', 'Garage')], default='AUTO', max_length=20),
        ),
    ]
