# Generated by Django 5.2.6 on 2026-05-28 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_alter_quote_product_type'),
        ('reference_data', '0006_mark_form_rule_seed_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='duration_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='reference_data.durationoption'),
        ),
        migrations.AddField(
            model_name='quote',
            name='product_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='reference_data.productreference'),
        ),
    ]
