# Generated by Django 5.2.6 on 2026-05-28 12:22

from django.db import migrations


def _normalized(value):
    if value is None:
        return ""
    return str(value).strip().upper()


def _single_value_map(references, fields):
    matches = {}
    duplicated_values = set()
    for reference in references:
        for field in fields:
            value = _normalized(getattr(reference, field, ""))
            if not value:
                continue
            if value in matches:
                duplicated_values.add(value)
            else:
                matches[value] = reference.pk
    for value in duplicated_values:
        matches.pop(value, None)
    return matches


def _duration_map(duration_options):
    matches = {}
    duplicated_values = set()
    for option in duration_options:
        candidates = [
            (option.duration, option.periodicity),
            (option.ass_duration, option.ass_periodicity),
        ]
        for duration, periodicity in candidates:
            if duration is None or not periodicity:
                continue
            value = (int(duration), _normalized(periodicity))
            if value in matches:
                duplicated_values.add(value)
            else:
                matches[value] = option.pk
    for value in duplicated_values:
        matches.pop(value, None)
    return matches


def backfill_quote_references(apps, schema_editor):
    Quote = apps.get_model("quotes", "Quote")
    ProductReference = apps.get_model("reference_data", "ProductReference")
    DurationOption = apps.get_model("reference_data", "DurationOption")

    product_matches = _single_value_map(
        ProductReference.objects.filter(is_active=True),
        ("code",),
    )
    duration_matches = _duration_map(DurationOption.objects.filter(is_active=True))

    for quote in Quote.objects.all().iterator():
        updates = {}
        if quote.product_reference_id is None:
            product_reference_id = product_matches.get(_normalized(quote.product_type))
            if product_reference_id:
                updates["product_reference_id"] = product_reference_id
        if quote.duration_option_id is None:
            duration_option_id = duration_matches.get(
                (quote.duration, _normalized(quote.periodicity))
            )
            if duration_option_id:
                updates["duration_option_id"] = duration_option_id
        if updates:
            Quote.objects.filter(pk=quote.pk).update(**updates)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_quote_duration_option_quote_product_reference'),
    ]

    operations = [
        migrations.RunPython(backfill_quote_references, noop_reverse),
    ]
