# Generated by Django 5.2.6 on 2026-05-28 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, unique=True)),
                ('ass_code', models.CharField(blank=True, max_length=120)),
                ('label', models.CharField(max_length=180)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'label', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, unique=True)),
                ('ass_code', models.CharField(blank=True, max_length=120)),
                ('label', models.CharField(max_length=180)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['sort_order', 'label', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, unique=True)),
                ('ass_code', models.CharField(blank=True, max_length=120)),
                ('label', models.CharField(max_length=180)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'label', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, unique=True)),
                ('ass_code', models.CharField(blank=True, max_length=120)),
                ('label', models.CharField(max_length=180)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'label', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DurationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, unique=True)),
                ('ass_code', models.CharField(blank=True, max_length=120)),
                ('label', models.CharField(max_length=180)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duration', models.PositiveSmallIntegerField()),
                ('periodicity', models.CharField(choices=[('JOURS', 'Jours'), ('MOIS', 'Mois'), ('ANNEES', 'Annees')], max_length=20)),
                ('ass_duration', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ass_periodicity', models.CharField(blank=True, max_length=20)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='duration_options', to='reference_data.productreference')),
            ],
            options={
                'ordering': ['sort_order', 'label', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, unique=True)),
                ('ass_code', models.CharField(blank=True, max_length=120)),
                ('label', models.CharField(max_length=180)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='reference_data.vehiclecategory')),
            ],
            options={
                'verbose_name_plural': 'vehicle sub categories',
                'ordering': ['sort_order', 'label', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, unique=True)),
                ('ass_code', models.CharField(blank=True, max_length=120)),
                ('label', models.CharField(max_length=180)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requires_trailer_section', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genres', to='reference_data.vehiclecategory')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='genres', to='reference_data.vehiclesubcategory')),
            ],
            options={
                'ordering': ['sort_order', 'label', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('field_name', models.CharField(max_length=120)),
                ('rule_type', models.CharField(choices=[('SHOW', 'Afficher'), ('HIDE', 'Masquer'), ('REQUIRED', 'Obligatoire'), ('READONLY', 'Lecture seule'), ('DEFAULT', 'Valeur par defaut')], max_length=20)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='form_rules', to='reference_data.productreference')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='form_rules', to='reference_data.vehiclecategory')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='form_rules', to='reference_data.vehiclegenre')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='form_rules', to='reference_data.vehiclesubcategory')),
            ],
            options={
                'ordering': ['priority', 'code', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VehicleUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, unique=True)),
                ('ass_code', models.CharField(blank=True, max_length=120)),
                ('label', models.CharField(max_length=180)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='reference_data.productreference')),
            ],
            options={
                'ordering': ['sort_order', 'label', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GuaranteeReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, unique=True)),
                ('ass_code', models.CharField(blank=True, max_length=120)),
                ('label', models.CharField(max_length=180)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ass_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('is_default_selected', models.BooleanField(default=False)),
                ('is_readonly', models.BooleanField(default=False)),
                ('products', models.ManyToManyField(blank=True, related_name='guarantees', to='reference_data.productreference')),
            ],
            options={
                'ordering': ['sort_order', 'label', 'id'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('ass_id__isnull', False)), fields=('ass_id',), name='reference_data_unique_guarantee_ass_id')],
            },
        ),
    ]
