# Generated by Django 5.2.6 on 2026-05-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0002_seed_initial_reference_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='durationoption',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='durationoption',
            name='source',
            field=models.CharField(choices=[('DOCUMENTATION', 'Documentation ASS'), ('POSTMAN', 'Collection Postman'), ('NATIVE_ACCOUNT', 'Compte natif ASS'), ('SANDBOX_VALIDATION', 'Validation sandbox'), ('INTERNAL', 'Interne Horus'), ('UNKNOWN', 'Inconnue')], default='INTERNAL', max_length=30),
        ),
        migrations.AddField(
            model_name='energytype',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='energytype',
            name='source',
            field=models.CharField(choices=[('DOCUMENTATION', 'Documentation ASS'), ('POSTMAN', 'Collection Postman'), ('NATIVE_ACCOUNT', 'Compte natif ASS'), ('SANDBOX_VALIDATION', 'Validation sandbox'), ('INTERNAL', 'Interne Horus'), ('UNKNOWN', 'Inconnue')], default='INTERNAL', max_length=30),
        ),
        migrations.AddField(
            model_name='formrule',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formrule',
            name='source',
            field=models.CharField(choices=[('DOCUMENTATION', 'Documentation ASS'), ('POSTMAN', 'Collection Postman'), ('NATIVE_ACCOUNT', 'Compte natif ASS'), ('SANDBOX_VALIDATION', 'Validation sandbox'), ('INTERNAL', 'Interne Horus'), ('UNKNOWN', 'Inconnue')], default='INTERNAL', max_length=30),
        ),
        migrations.AddField(
            model_name='guaranteereference',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guaranteereference',
            name='source',
            field=models.CharField(choices=[('DOCUMENTATION', 'Documentation ASS'), ('POSTMAN', 'Collection Postman'), ('NATIVE_ACCOUNT', 'Compte natif ASS'), ('SANDBOX_VALIDATION', 'Validation sandbox'), ('INTERNAL', 'Interne Horus'), ('UNKNOWN', 'Inconnue')], default='INTERNAL', max_length=30),
        ),
        migrations.AddField(
            model_name='productreference',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productreference',
            name='source',
            field=models.CharField(choices=[('DOCUMENTATION', 'Documentation ASS'), ('POSTMAN', 'Collection Postman'), ('NATIVE_ACCOUNT', 'Compte natif ASS'), ('SANDBOX_VALIDATION', 'Validation sandbox'), ('INTERNAL', 'Interne Horus'), ('UNKNOWN', 'Inconnue')], default='INTERNAL', max_length=30),
        ),
        migrations.AddField(
            model_name='vehiclebrand',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiclebrand',
            name='source',
            field=models.CharField(choices=[('DOCUMENTATION', 'Documentation ASS'), ('POSTMAN', 'Collection Postman'), ('NATIVE_ACCOUNT', 'Compte natif ASS'), ('SANDBOX_VALIDATION', 'Validation sandbox'), ('INTERNAL', 'Interne Horus'), ('UNKNOWN', 'Inconnue')], default='INTERNAL', max_length=30),
        ),
        migrations.AddField(
            model_name='vehiclecategory',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiclecategory',
            name='source',
            field=models.CharField(choices=[('DOCUMENTATION', 'Documentation ASS'), ('POSTMAN', 'Collection Postman'), ('NATIVE_ACCOUNT', 'Compte natif ASS'), ('SANDBOX_VALIDATION', 'Validation sandbox'), ('INTERNAL', 'Interne Horus'), ('UNKNOWN', 'Inconnue')], default='INTERNAL', max_length=30),
        ),
        migrations.AddField(
            model_name='vehiclegenre',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiclegenre',
            name='source',
            field=models.CharField(choices=[('DOCUMENTATION', 'Documentation ASS'), ('POSTMAN', 'Collection Postman'), ('NATIVE_ACCOUNT', 'Compte natif ASS'), ('SANDBOX_VALIDATION', 'Validation sandbox'), ('INTERNAL', 'Interne Horus'), ('UNKNOWN', 'Inconnue')], default='INTERNAL', max_length=30),
        ),
        migrations.AddField(
            model_name='vehiclesubcategory',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiclesubcategory',
            name='source',
            field=models.CharField(choices=[('DOCUMENTATION', 'Documentation ASS'), ('POSTMAN', 'Collection Postman'), ('NATIVE_ACCOUNT', 'Compte natif ASS'), ('SANDBOX_VALIDATION', 'Validation sandbox'), ('INTERNAL', 'Interne Horus'), ('UNKNOWN', 'Inconnue')], default='INTERNAL', max_length=30),
        ),
        migrations.AddField(
            model_name='vehicleusage',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicleusage',
            name='source',
            field=models.CharField(choices=[('DOCUMENTATION', 'Documentation ASS'), ('POSTMAN', 'Collection Postman'), ('NATIVE_ACCOUNT', 'Compte natif ASS'), ('SANDBOX_VALIDATION', 'Validation sandbox'), ('INTERNAL', 'Interne Horus'), ('UNKNOWN', 'Inconnue')], default='INTERNAL', max_length=30),
        ),
    ]
