# Generated by Django 5.2.6 on 2026-05-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0004_mark_reference_data_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='formrule',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
