# Generated by Django 5.2.6 on 2026-05-21 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('PAYMENT_CONFIRMED', 'Paiement confirme'), ('CONTRACT_ISSUED', 'Contrat emis'), ('COMMISSION_GENERATED', 'Commission generee'), ('COMMISSION_PAID', 'Commission payee')], max_length=40)),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField(blank=True)),
                ('target_type', models.CharField(blank=True, max_length=120)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='groups.partnergroup')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
