# Generated by Django 5.2.6 on 2026-05-21 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('WALLET_CREDITED', 'Wallet credite'), ('WALLET_DEBITED', 'Wallet debite'), ('PAYMENT_CONFIRMED', 'Paiement confirme'), ('CONTRACT_ISSUED', 'Contrat emis'), ('COMMISSION_GENERATED', 'Commission generee'), ('COMMISSION_PAID', 'Commission payee')], max_length=40)),
                ('target_type', models.CharField(blank=True, max_length=120)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('partner_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='groups.partnergroup')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
