# Generated by Django 5.2.6 on 2026-05-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('WALLET_CREDITED', 'Wallet credite'), ('WALLET_DEBITED', 'Wallet debite'), ('PAYMENT_CONFIRMED', 'Paiement confirme'), ('CONTRACT_ISSUED', 'Contrat emis'), ('COMMISSION_GENERATED', 'Commission generee'), ('COMMISSION_PAID', 'Commission payee'), ('CLIENT_ACCESS_TOKEN_CREATED', 'Jeton client cree'), ('CLIENT_ACCESS_LINK_SENT', 'Lien client envoye'), ('CLIENT_ACCESS_TOKEN_USED', 'Jeton client utilise'), ('CLIENT_ACCESS_TOKEN_REVOKED', 'Jeton client revoque'), ('CLIENT_ACCESS_TOKEN_ROTATED', 'Jeton client renouvele'), ('CLIENT_ACCESS_OTP_CREATED', 'OTP client cree'), ('CLIENT_ACCESS_OTP_SENT', 'OTP client envoye'), ('CLIENT_ACCESS_OTP_VERIFIED', 'OTP client valide'), ('CLIENT_ACCESS_OTP_FAILED', 'OTP client refuse'), ('CLIENT_ACCESS_OTP_REVOKED', 'OTP client revoque')], max_length=40),
        ),
    ]
