# Generated by Django 5.2.6 on 2026-05-28 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0006_mark_form_rule_seed_metadata'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='brand_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='reference_data.vehiclebrand'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='energy_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='reference_data.energytype'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='genre_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='reference_data.vehiclegenre'),
        ),
    ]
