# Generated by Django 5.2.6 on 2026-05-28 12:22

from django.db import migrations


def _normalized(value):
    if value is None:
        return ""
    return str(value).strip().upper()


def _single_match_map(references, fields):
    matches = {}
    duplicated_values = set()
    for reference in references:
        for field in fields:
            value = _normalized(getattr(reference, field, ""))
            if not value:
                continue
            if value in matches:
                duplicated_values.add(value)
            else:
                matches[value] = reference.pk
    for value in duplicated_values:
        matches.pop(value, None)
    return matches


def backfill_vehicle_references(apps, schema_editor):
    Vehicle = apps.get_model("vehicles", "Vehicle")
    VehicleBrand = apps.get_model("reference_data", "VehicleBrand")
    VehicleGenre = apps.get_model("reference_data", "VehicleGenre")
    EnergyType = apps.get_model("reference_data", "EnergyType")

    brand_matches = _single_match_map(
        VehicleBrand.objects.filter(is_active=True),
        ("label", "code", "ass_code"),
    )
    genre_matches = _single_match_map(
        VehicleGenre.objects.filter(is_active=True),
        ("code", "ass_code", "label"),
    )
    energy_matches = _single_match_map(
        EnergyType.objects.filter(is_active=True),
        ("code", "ass_code", "label"),
    )

    for vehicle in Vehicle.objects.all().iterator():
        updates = {}
        if vehicle.brand_reference_id is None:
            brand_reference_id = brand_matches.get(_normalized(vehicle.brand))
            if brand_reference_id:
                updates["brand_reference_id"] = brand_reference_id
        if vehicle.genre_reference_id is None:
            genre_reference_id = genre_matches.get(_normalized(vehicle.genre))
            if genre_reference_id:
                updates["genre_reference_id"] = genre_reference_id
        if vehicle.energy_reference_id is None:
            energy_reference_id = energy_matches.get(_normalized(vehicle.energy))
            if energy_reference_id:
                updates["energy_reference_id"] = energy_reference_id
        if updates:
            Vehicle.objects.filter(pk=vehicle.pk).update(**updates)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_brand_reference_vehicle_energy_reference_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_vehicle_references, noop_reverse),
    ]
