# Generated by Django 5.2.6 on 2026-05-21 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(choices=[('INDIVIDUAL', 'Personne physique'), ('COMPANY', 'Personne morale')], default='INDIVIDUAL', max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('company_name', models.CharField(blank=True, max_length=180)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=32)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('identity_number', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clients', to=settings.AUTH_USER_MODEL)),
                ('partner_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='groups.partnergroup')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('partner_group', 'phone'), name='clients_unique_phone_per_group'), models.CheckConstraint(condition=models.Q(models.Q(('client_type', 'INDIVIDUAL'), models.Q(('first_name__gt', ''), ('last_name__gt', ''), _connector='OR')), models.Q(('client_type', 'COMPANY'), ('company_name__gt', '')), _connector='OR'), name='clients_required_display_name')],
            },
        ),
    ]
