# Generated by Django 5.2.6 on 2026-05-25 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clientaccesstoken'),
        ('contracts', '0002_contract_diotali_urls'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAccessOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_hash', models.CharField(max_length=64)),
                ('purpose', models.CharField(choices=[('ATTESTATION_DOWNLOAD', 'Telechargement attestation'), ('CARTE_BRUNE_DOWNLOAD', 'Telechargement carte brune')], max_length=40)),
                ('delivery_channel', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('MANUAL', 'Manuel')], default='MANUAL', max_length=20)),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='clients.clientaccesstoken')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_otps', to='clients.client')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_access_otps', to='contracts.contract')),
                ('partner_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_access_otps', to='groups.partnergroup')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['access_token', 'purpose', 'otp_hash'], name='clients_otp_lookup_idx')],
            },
        ),
    ]
