# Generated by Django 5.2.6 on 2026-05-24 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('WAVE', 'Wave'), ('ORANGE_MONEY', 'Orange Money')], max_length=20)),
                ('event_id', models.CharField(max_length=160)),
                ('event_type', models.CharField(blank=True, max_length=120)),
                ('provider_reference', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('RECEIVED', 'Recu'), ('PROCESSED', 'Traite'), ('IGNORED', 'Ignore'), ('FAILED', 'Echoue')], default='RECEIVED', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='payments.payment')),
            ],
            options={
                'ordering': ['-received_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'event_id'), name='payment_webhook_unique_event_per_provider')],
            },
        ),
    ]
