# Generated by Django 5.2.6 on 2026-05-21 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('groups', '0001_initial'),
        ('payments', '0001_initial'),
        ('quotes', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('READY_TO_ISSUE', 'Pret a emettre'), ('ISSUED', 'Emis'), ('CANCELLED', 'Annule')], default='READY_TO_ISSUE', max_length=20)),
                ('contract_number', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('attestation_reference', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('qr_code_reference', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='clients.client')),
                ('contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL)),
                ('partner_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='groups.partnergroup')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='payments.payment')),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='quotes.quote')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
