# Generated by Django 5.2.6 on 2026-05-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="attestation_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="contract",
            name="carte_brune_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
